# By default, this docker-compose file will start a lotus fullnode
#
# Some directives have been left commented out so they serve as an
# example for more advanced use.
#
# To provide a custom configuration file, or automatically import
# a wallet, uncomment the "configs" or "secrets" sections.
# 
# start on a single node:
#
#    docker-compose up
#
# start on docker swarm:
#
#    docker swarm init (if you haven't already)
#    docker stack deploy -c docker-compose.yaml mylotuscluster
#
# for more information, please visit docs.filecoin.io

version: "3.8"

volumes:
  lotus-repo:
  lotus-miner-repo:
  lotus-worker-repo:
  lotus-data-repo:
    external: true
    name: lotus-data-repo
  parameters:
    external: true
    name: lotus-parameters

configs:
  lotus-config-toml:
    file: ./exported/lotus/config.toml
  lotus-miner-config-toml:
    file: ./exported/lotus-miner/config.toml

secrets:
  lotus-wallet:
    file: ./exported/lotus/wallet

services:
  lotus:
    image: he426100/lotus:v1.13.1-dev
    volumes:
      - parameters:/var/tmp/filecoin-proof-parameters
      - lotus-repo:/var/lib/lotus
      - lotus-data-repo:/data
    ports:
      - 1234:1234
    environment:
      - LOTUS_API_LISTENADDRESS=/ip4/0.0.0.0/tcp/1234/http
      - DOCKER_LOTUS_IMPORT_SNAPSHOT=
      - DOCKER_LOTUS_IMPORT_WALLET=/tmp/wallet
      - LOTUS_JAEGER_AGENT_HOST=jaeger
      - LOTUS_JAEGER_AGENT_PORT=6831
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    configs:
        - source: lotus-config-toml
          target: /var/lib/lotus/config.toml
    secrets:
        - source: lotus-wallet
          target: /tmp/wallet
    command:
      - daemon --lotus-make-genesis=/data/devgen.car --genesis-template=/data/localnet.json --bootstrap=false

  #      
  # Uncomment to run miner software
  #
  # lotus-miner:
  #   image: he426100/lotus-miner:v1.13.1-dev
  #   volumes:
  #     - parameters:/var/tmp/filecoin-proof-parameters
  #     - lotus-miner-repo:/var/lib/lotus-miner
  #     - lotus-data-repo:/data
  #   depends_on:
  #     - lotus
  #   ports:
  #     - 1245:2345
  #   environment:
  #     - LOTUS_API_LISTENADDRESS=/ip4/0.0.0.0/tcp/2345/http
  #     - FULLNODE_API_INFO=/dns/lotus/tcp/1234/http
  #     - DOCKER_LOTUS_MINER_INIT=true
  #     - DOCKER_LOTUS_MINER_INIT_ARGS="--genesis-miner --actor=t01000 --sector-size=2KiB --pre-sealed-sectors=/data/.genesis-sectors --pre-sealed-metadata=/data/.genesis-sectors/pre-seal-t01000.json --nosync"
  #     - LOTUS_JAEGER_AGENT_HOST=jaeger
  #     - LOTUS_JAEGER_AGENT_PORT=6831
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 30s
  #   configs:
  #     - source: lotus-miner-config-toml
  #       target: /var/lib/lotus-miner/config.toml
  #   command:
  #     - run --nosync
  # lotus-worker:
  #   build:
  #     context: .
  #     target: lotus-worker
  #     dockerfile: Dockerfile.lotus
  #   image: filecoin/lotus-worker
  #   volumes:
  #     - parameters:/var/tmp/filecoin-proof-parameters
  #     - lotus-worker-repo:/var/lib/lotus-worker
  #   depends_on:
  #     - lotus-worker
  #   environment:
  #     - MINER_API_INFO=/dns/lotus-miner/tcp/1234/http
  #     - LOTUS_JAEGER_AGENT_HOST=jaeger
  #     - LOTUS_JAEGER_AGENT_PORT=6831
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 30s
  #       replicas: 2
  #   command:
  #     - run
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
